-- create_tables.sql

-- Create schema if it does not exist
CREATE SCHEMA IF NOT EXISTS %s;

CREATE TABLE IF NOT EXISTS %s.patient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR(10) NOT NULL,
    contact_number VARCHAR(20),
    email VARCHAR(255),
    address TEXT,
    emergency_contact VARCHAR(20)
    );


CREATE TABLE IF NOT EXISTS %s.doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    specialty VARCHAR(100),
    qualification VARCHAR(100),
    experience_years INT,
    contact_number VARCHAR(15),
    email VARCHAR(100)
);




